/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as DifficultyRouteImport } from './routes/difficulty'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersUserIdRouteImport } from './routes/users/$userId'
import { Route as ChallengeCompleteRouteImport } from './routes/challenge/complete'
import { Route as ChallengeChallengeIdRouteImport } from './routes/challenge/$challengeId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const DifficultyRoute = DifficultyRouteImport.update({
  id: '/difficulty',
  path: '/difficulty',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeCompleteRoute = ChallengeCompleteRouteImport.update({
  id: '/challenge/complete',
  path: '/challenge/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeChallengeIdRoute = ChallengeChallengeIdRouteImport.update({
  id: '/challenge/$challengeId',
  path: '/challenge/$challengeId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/difficulty': typeof DifficultyRoute
  '/sign-in': typeof SignInRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
  '/challenge/complete': typeof ChallengeCompleteRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/difficulty': typeof DifficultyRoute
  '/sign-in': typeof SignInRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
  '/challenge/complete': typeof ChallengeCompleteRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/difficulty': typeof DifficultyRoute
  '/sign-in': typeof SignInRoute
  '/challenge/$challengeId': typeof ChallengeChallengeIdRoute
  '/challenge/complete': typeof ChallengeCompleteRoute
  '/users/$userId': typeof UsersUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/difficulty'
    | '/sign-in'
    | '/challenge/$challengeId'
    | '/challenge/complete'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/difficulty'
    | '/sign-in'
    | '/challenge/$challengeId'
    | '/challenge/complete'
    | '/users/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/difficulty'
    | '/sign-in'
    | '/challenge/$challengeId'
    | '/challenge/complete'
    | '/users/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DifficultyRoute: typeof DifficultyRoute
  SignInRoute: typeof SignInRoute
  ChallengeChallengeIdRoute: typeof ChallengeChallengeIdRoute
  ChallengeCompleteRoute: typeof ChallengeCompleteRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/difficulty': {
      id: '/difficulty'
      path: '/difficulty'
      fullPath: '/difficulty'
      preLoaderRoute: typeof DifficultyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/complete': {
      id: '/challenge/complete'
      path: '/challenge/complete'
      fullPath: '/challenge/complete'
      preLoaderRoute: typeof ChallengeCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$challengeId': {
      id: '/challenge/$challengeId'
      path: '/challenge/$challengeId'
      fullPath: '/challenge/$challengeId'
      preLoaderRoute: typeof ChallengeChallengeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DifficultyRoute: DifficultyRoute,
  SignInRoute: SignInRoute,
  ChallengeChallengeIdRoute: ChallengeChallengeIdRoute,
  ChallengeCompleteRoute: ChallengeCompleteRoute,
  UsersUserIdRoute: UsersUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
